# Generated by Django 3.1.4 on 2020-12-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
                ('nombredeMascota', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMascota', models.CharField(max_length=30)),
                ('tipoMascota', models.CharField(max_length=30)),
                ('raza', models.CharField(max_length=30)),
                ('edad', models.CharField(max_length=30)),
                ('sexo', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=30)),
            ],
        ),
    ]
